### ISSUE TITLE
Reports 100% CPU used

### ISSUE THREAD

**Issue by Calinou** [mashlol/mintr#1]
Mintr reports 100% CPU used, but I'm only actually using 10% or so (according to `htop`).

http://mt.nerdpol.ovh:3000/

**Comment by mashlol** [comment]
Lol damn, nothing works :(

I'm using https://github.com/husanu/nodejs-cpu-usage for this, perhaps we should file a bug there.  Or, I could probably sum all the CPU usages of the processes to get a similar result.

Thanks for all these bug reports btw, much appreciated.

**Comment by mashlol** [comment]
Should be fixed in 0.0.7
