### ISSUE TITLE
graphs doesnt work on wan

### ISSUE THREAD

**Issue by swetoast** [mashlol/mintr#11]
i get the graphs working on lan but when i look at the same page on wan side the graphs doesn't load

**Comment by mashlol** [comment]
@swetoast What OS?

**Comment by swetoast** [comment]
Raspbian GNU/Linux 8.0 (jessie) (Kernel Version: 3.18.0-trunk-rpi) again it works perfect in lan but wan and i get no graphs

**Comment by mashlol** [comment]
Could you check the network tab on chrome and check if the websocket was able to connect?  It's possible that you are able to load the http page but not connect to the websocket where the data comes from

**Comment by swetoast** [comment]
Seems like its loading but still no graph
![mintr](https://cloud.githubusercontent.com/assets/2525304/7481599/60cee2a2-f371-11e4-9769-f2d48135be16.png)

**Comment by mashlol** [comment]
Does any other info load, like uptime?

**Comment by swetoast** [comment]
nothing thats what i find so wierd

**Comment by mashlol** [comment]
Could you go back into network tab, click on the last request labelled `?EIO=3&...` (maybe not the last one, just click until you see a frame tab) and click on the frame tab?  You should see something like this:

![capture](https://cloud.githubusercontent.com/assets/1039240/7487413/1154d1a0-f385-11e4-82ed-db83ecd973cf.PNG)

Let me know what you actually see

**Comment by swetoast** [comment]
Found something that could be a clue

![mintr2](https://cloud.githubusercontent.com/assets/2525304/7487483/d1b80a06-f3b8-11e4-8a98-9a71e097d7b6.png)

**Comment by swetoast** [comment]
found the error seems it doesn't like the google data saver used for mobile platforms and as an extension not sure if there is something you can do about that or not in anycase it works for me now

https://chrome.google.com/webstore/detail/data-saver-beta/pfmgfdlgomnbgkofeojodiodmgpgmkac?hl=en

links to the ext and for mobile just check settings for chrome

**Comment by mashlol** [comment]
Huh, interesting.  Sounds like its a bug in that extension, since it's not supposed to change the behavior of the websites you visit, just reduce the bandwidth.

**Comment by swetoast** [comment]
yeah not easy to report those kinda bugs to google
